// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCd7Jptmp-yQUGeYliCtyf33nnoq7B3INw',
    appId: '1:759159093073:web:30ad6b405cea779c99c570',
    messagingSenderId: '759159093073',
    projectId: 'enrollment-8bef4',
    authDomain: 'enrollment-8bef4.firebaseapp.com',
    databaseURL: 'https://enrollment-8bef4-default-rtdb.firebaseio.com',
    storageBucket: 'enrollment-8bef4.appspot.com',
    measurementId: 'G-TT4RW0FNPY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXwuEomtCS4JLwz-BLikeeL8d6fV6078w',
    appId: '1:759159093073:android:0e2ab21ea500209899c570',
    messagingSenderId: '759159093073',
    projectId: 'enrollment-8bef4',
    databaseURL: 'https://enrollment-8bef4-default-rtdb.firebaseio.com',
    storageBucket: 'enrollment-8bef4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnA4Qb0WChH0nvDm7j2-osYRcMWBXtgVQ',
    appId: '1:759159093073:ios:192158a7a063ab8799c570',
    messagingSenderId: '759159093073',
    projectId: 'enrollment-8bef4',
    databaseURL: 'https://enrollment-8bef4-default-rtdb.firebaseio.com',
    storageBucket: 'enrollment-8bef4.appspot.com',
    iosClientId: '759159093073-k76637tr42am2ton0buj8rpgfur4c5eg.apps.googleusercontent.com',
    iosBundleId: 'com.example.webSchool',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnA4Qb0WChH0nvDm7j2-osYRcMWBXtgVQ',
    appId: '1:759159093073:ios:6ebe5c3b262daae899c570',
    messagingSenderId: '759159093073',
    projectId: 'enrollment-8bef4',
    databaseURL: 'https://enrollment-8bef4-default-rtdb.firebaseio.com',
    storageBucket: 'enrollment-8bef4.appspot.com',
    iosClientId: '759159093073-tp0ctoftbkl84jfgj5ie0p5pr95ilk7q.apps.googleusercontent.com',
    iosBundleId: 'com.example.webSchool.RunnerTests',
  );
}
